# Generated by Django 2.2 on 2019-04-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useropenid',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useropenid',
            name='avatar',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='useropenid',
            name='tags',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='useropenid',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
